-- Este script viene de el equema que solo tiene rubros y productos
-- y su relacion N a N

-- Fernanda Valle
-- 09/09/2018

-- MySQL Script generated by MySQL Workbench
-- Sun Sep  9 11:57:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`rubros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rubros` (
  `idRubro` INT NOT NULL,
  `rubro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRubro`),
  UNIQUE INDEX `rubro_UNIQUE` (`rubro` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `idProducto` INT NOT NULL,
  `producto` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`etiqueta` (
  `idRubro` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idRubro`, `idProducto`),
  INDEX `idx_idProducto` (`idProducto` ASC),
  INDEX `idx_idRurbo` (`idRubro` ASC),
  INDEX `idx_idRubroIdProudcto` (`idRubro` ASC, `idProducto` ASC),
  CONSTRAINT `fk_idRubro`
    FOREIGN KEY (`idRubro`)
    REFERENCES `mydb`.`rubros` (`idRubro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idProdudcto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
